version: 0.2
env:
  variables:
    INPUT_FILE: "app.yaml"
    OUTPUT_FILE: "post-app.yaml"
phases:
  install:
    commands:
      - pip install --upgrade awscli
      - apt-get update
      - apt-get -y install openssh-client
      - cat /etc/lsb-release
      - curl -s -O https://deb.nodesource.com/node_6.x/pool/main/n/nodejs/nodejs_6.10.0-1nodesource1~trusty1_amd64.deb
      - dpkg -i nodejs_6.10.0-1nodesource1~trusty1_amd64.deb
      - npm install -g n  
      - n 6.10.0
      - node -v
      - npm install yarn -g 
      - yarn install
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - echo Build completed on `date`
      - cd ./dist/build/
      - zip /tmp/userIndex.zip userIndex.js
      - md5sum /tmp/userIndex.zip
      - aws s3 cp /tmp/userIndex.zip s3://dev-ms-api-codebuild-prototype/deploy/userIndex.zip
      - aws s3 cp ../../app.yaml s3://dev-ms-api-codebuild-prototype/deploy/app.yaml
      - cd ../../
      - echo "Getting beta.json"
      - wget https://s3.amazonaws.com/ctx-dev-pipeline/beta.json
      # - aws cloudformation deploy --template-file ../../app.yaml --stack-name $STACK_NAME 
      # - aws cloudformation describe-stack-events --stack-name $STACK_NAME 
      - aws cloudformation package --template-file app.yaml --s3-bucket ctx-dev-pipeline --output-template-file post-app.yaml
artifacts:
    files:
        - post-app.yaml
        - beta.json  